version: '3.1'

services:
  dream-web:
    depends_on:
      - dream-server
      - dream-auth
    build:
      context: services/web
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/usr/src/app/src
    networks:
      - client-server
      - server-auth

  dream-server:
    depends_on:
      - dream-db
      - dream-auth
    build:
      context: services/server
    ports:
      - '4001:4001'
    volumes:
      - ./server/src:/usr/src/app/src
    networks:
      - server-db
      - client-server
      - server-auth

  dream-auth:
    depends_on:
      - dream-db
    build:
      context: services/auth
    ports:
      - '4001:4001'
    networks:
      - server-db
      - web-server

  dream-db:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - '27019:27019'
    networks:
      - server-db
    volumes:
      - dream-mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: dream

networks:
  server-db:
    driver: bridge
  server-auth:
    driver: bridge
  web-server:
    driver: bridge

volumes:
  dream-mongo:
